//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikExample.GoldPriceFreeWeb {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://freewebservicesx.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://freewebservicesx.com/", ConfigurationName="GoldPriceFreeWeb.GetGoldPriceSoap")]
    public interface GetGoldPriceSoap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://freewebservicesx.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://freewebservicesx.com/GetCurrentGoldPrice", ReplyAction="*")]
        TelerikExample.GoldPriceFreeWeb.GetCurrentGoldPriceResponse GetCurrentGoldPrice(TelerikExample.GoldPriceFreeWeb.GetCurrentGoldPriceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentGoldPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentGoldPrice", Namespace="http://freewebservicesx.com/", Order=0)]
        public TelerikExample.GoldPriceFreeWeb.GetCurrentGoldPriceRequestBody Body;
        
        public GetCurrentGoldPriceRequest() {
        }
        
        public GetCurrentGoldPriceRequest(TelerikExample.GoldPriceFreeWeb.GetCurrentGoldPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://freewebservicesx.com/")]
    public partial class GetCurrentGoldPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public GetCurrentGoldPriceRequestBody() {
        }
        
        public GetCurrentGoldPriceRequestBody(string UserName, string Password) {
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentGoldPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentGoldPriceResponse", Namespace="http://freewebservicesx.com/", Order=0)]
        public TelerikExample.GoldPriceFreeWeb.GetCurrentGoldPriceResponseBody Body;
        
        public GetCurrentGoldPriceResponse() {
        }
        
        public GetCurrentGoldPriceResponse(TelerikExample.GoldPriceFreeWeb.GetCurrentGoldPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://freewebservicesx.com/")]
    public partial class GetCurrentGoldPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TelerikExample.GoldPriceFreeWeb.ArrayOfString GetCurrentGoldPriceResult;
        
        public GetCurrentGoldPriceResponseBody() {
        }
        
        public GetCurrentGoldPriceResponseBody(TelerikExample.GoldPriceFreeWeb.ArrayOfString GetCurrentGoldPriceResult) {
            this.GetCurrentGoldPriceResult = GetCurrentGoldPriceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetGoldPriceSoapChannel : TelerikExample.GoldPriceFreeWeb.GetGoldPriceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetGoldPriceSoapClient : System.ServiceModel.ClientBase<TelerikExample.GoldPriceFreeWeb.GetGoldPriceSoap>, TelerikExample.GoldPriceFreeWeb.GetGoldPriceSoap {
        
        public GetGoldPriceSoapClient() {
        }
        
        public GetGoldPriceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetGoldPriceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetGoldPriceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetGoldPriceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TelerikExample.GoldPriceFreeWeb.GetCurrentGoldPriceResponse TelerikExample.GoldPriceFreeWeb.GetGoldPriceSoap.GetCurrentGoldPrice(TelerikExample.GoldPriceFreeWeb.GetCurrentGoldPriceRequest request) {
            return base.Channel.GetCurrentGoldPrice(request);
        }
        
        public TelerikExample.GoldPriceFreeWeb.ArrayOfString GetCurrentGoldPrice(string UserName, string Password) {
            TelerikExample.GoldPriceFreeWeb.GetCurrentGoldPriceRequest inValue = new TelerikExample.GoldPriceFreeWeb.GetCurrentGoldPriceRequest();
            inValue.Body = new TelerikExample.GoldPriceFreeWeb.GetCurrentGoldPriceRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            TelerikExample.GoldPriceFreeWeb.GetCurrentGoldPriceResponse retVal = ((TelerikExample.GoldPriceFreeWeb.GetGoldPriceSoap)(this)).GetCurrentGoldPrice(inValue);
            return retVal.Body.GetCurrentGoldPriceResult;
        }
    }
}
