// <copyright file="FileSystemTest.ReadAllText.g.cs" company="Microsoft">Copyright © Microsoft 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace MyMath
{
    public partial class FileSystemTest
    {
[TestMethod]
[PexGeneratedBy(typeof(FileSystemTest))]
public void ReadAllText907()
{
    string s;
    s = this.ReadAllText((string)null);
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(FileSystemTest))]
public void ReadAllText492()
{
    string s;
    s = this.ReadAllText("\0");
    Assert.AreEqual<string>("", s);
}
    }
}
