//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikExample.LondonGoldSilverFix {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webservicex.net", ConfigurationName="LondonGoldSilverFix.LondonGoldAndSilverFixSoap")]
    public interface LondonGoldAndSilverFixSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webservicex.net/GetLondonGoldAndSilverFix", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TelerikExample.LondonGoldSilverFix.GetLondonGoldAndSilverFixResponse GetLondonGoldAndSilverFix(TelerikExample.LondonGoldSilverFix.GetLondonGoldAndSilverFixRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webservicex.net")]
    public partial class LondonMarketData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float gold_AM_USDField;
        
        private float gold_AM_STGField;
        
        private float gold_AM_EURField;
        
        private float gold_PM_USDField;
        
        private float gold_PM_STGField;
        
        private float gold_PM_EURField;
        
        private float silver_CENTSField;
        
        private float silver_PENCEField;
        
        private float silver_EURField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float Gold_AM_USD {
            get {
                return this.gold_AM_USDField;
            }
            set {
                this.gold_AM_USDField = value;
                this.RaisePropertyChanged("Gold_AM_USD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float Gold_AM_STG {
            get {
                return this.gold_AM_STGField;
            }
            set {
                this.gold_AM_STGField = value;
                this.RaisePropertyChanged("Gold_AM_STG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float Gold_AM_EUR {
            get {
                return this.gold_AM_EURField;
            }
            set {
                this.gold_AM_EURField = value;
                this.RaisePropertyChanged("Gold_AM_EUR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float Gold_PM_USD {
            get {
                return this.gold_PM_USDField;
            }
            set {
                this.gold_PM_USDField = value;
                this.RaisePropertyChanged("Gold_PM_USD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float Gold_PM_STG {
            get {
                return this.gold_PM_STGField;
            }
            set {
                this.gold_PM_STGField = value;
                this.RaisePropertyChanged("Gold_PM_STG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public float Gold_PM_EUR {
            get {
                return this.gold_PM_EURField;
            }
            set {
                this.gold_PM_EURField = value;
                this.RaisePropertyChanged("Gold_PM_EUR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public float Silver_CENTS {
            get {
                return this.silver_CENTSField;
            }
            set {
                this.silver_CENTSField = value;
                this.RaisePropertyChanged("Silver_CENTS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public float Silver_PENCE {
            get {
                return this.silver_PENCEField;
            }
            set {
                this.silver_PENCEField = value;
                this.RaisePropertyChanged("Silver_PENCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public float Silver_EUR {
            get {
                return this.silver_EURField;
            }
            set {
                this.silver_EURField = value;
                this.RaisePropertyChanged("Silver_EUR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLondonGoldAndSilverFix", WrapperNamespace="http://www.webservicex.net", IsWrapped=true)]
    public partial class GetLondonGoldAndSilverFixRequest {
        
        public GetLondonGoldAndSilverFixRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLondonGoldAndSilverFixResponse", WrapperNamespace="http://www.webservicex.net", IsWrapped=true)]
    public partial class GetLondonGoldAndSilverFixResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.webservicex.net", Order=0)]
        public TelerikExample.LondonGoldSilverFix.LondonMarketData GetLondonGoldAndSilverFixResult;
        
        public GetLondonGoldAndSilverFixResponse() {
        }
        
        public GetLondonGoldAndSilverFixResponse(TelerikExample.LondonGoldSilverFix.LondonMarketData GetLondonGoldAndSilverFixResult) {
            this.GetLondonGoldAndSilverFixResult = GetLondonGoldAndSilverFixResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LondonGoldAndSilverFixSoapChannel : TelerikExample.LondonGoldSilverFix.LondonGoldAndSilverFixSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LondonGoldAndSilverFixSoapClient : System.ServiceModel.ClientBase<TelerikExample.LondonGoldSilverFix.LondonGoldAndSilverFixSoap>, TelerikExample.LondonGoldSilverFix.LondonGoldAndSilverFixSoap {
        
        public LondonGoldAndSilverFixSoapClient() {
        }
        
        public LondonGoldAndSilverFixSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LondonGoldAndSilverFixSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LondonGoldAndSilverFixSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LondonGoldAndSilverFixSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TelerikExample.LondonGoldSilverFix.GetLondonGoldAndSilverFixResponse GetLondonGoldAndSilverFix(TelerikExample.LondonGoldSilverFix.GetLondonGoldAndSilverFixRequest request) {
            return base.Channel.GetLondonGoldAndSilverFix(request);
        }
    }
}
